# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Seth
last_name: Watts
email: sbwatts@txstate.edu
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Assistant Professor, School of Criminal Justice and Criminology, Texas State University.
  Researcher in policing, technology, and public health.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

icon: ☕️ # the emoji used as the favicon
url: https://www.sethbwatts.com # the base hostname & protocol for your site
baseurl: # should be empty string if your site is deployed at root
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo name and version of the al-folio theme
repo: alshedivat/al-folio
version: 0.12.0

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: sBwatts
gitlab_username:
x_username: SethBWatts
linkedin_username: sethwatts1
scholar_userid: _zgKKS0AAAAJ
orcid_id: 0000-0002-5108-9055
research_gate_profile:

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name:
blog_nav_title:
blog_description: using the al-folio theme
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
giscus:
  repo:
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  lang: en

disqus_shortname:

external_sources:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: false
  scrollable: true
  limit: 5

latest_posts:
  enabled: false
  scrollable: true
  limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile.lock
  - LICENSE
  - vendor
  - data/
  - research/
  - '*.qmd'
  - '*.Rmd'
  - _quarto.yml
  - call-python.R
  - call-scholar-stats.R
  - requirements.txt
  - open-alex.R
  - save_pubs.R
  - fetch-scholar-stats.py
  - _publications.yml
  - _site/
  - archive/
  - teaching/
  - website.Rproj
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll/scholar
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Watts]
  first_name: [Seth, S.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Theming
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# Remote theme
# -----------------------------------------------------------------------------

remote_theme: alshedivat/al-folio@v0.16.3
