---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Seth Watts, PhD

jobtitle: "Assistant Professor, Criminal Justice & Criminology"
address: "Texas State University · San Marcos, TX"
fontawesome: yes
email: sbwatts@txstate.edu
github: sbwatts
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
#phone: "+353 1 408 4800"
web: sethbwatts.com
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

header-includes:
  - \usepackage{xcolor}
  - \definecolor{txst}{HTML}{501214}
  
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: txst
urlcolor: txst
---

# Education

*Arizona State University*

PhD, Criminology and Criminal Justice \hfill 2024

MS, Criminology and Criminal Justice  \hfill 2021

\vspace{1.0em}

*Bowling Green State University* 

BA, Psychology \hfill 2019

# Academic Positions

Assistant Professor | Texas State University \hfill 2025-

## Academic Affiliations

Research Affiliate, [Texas Crime and Justice Center (TCJC)](https://www.cj.txst.edu/research/centers-labs/tcjc.html) | Texas State University \hfill 2025-

## Previous Positions

Postdoctoral Researcher | Arizona State University \hfill 2024-2025

Graduate Research Assistant | Arizona State University \hfill 2020-2024

# Work in Progress

Watts, S., Orosco, C., & White, D. M. De-escalation Training: A Comparative Review of Tempe, ICAT, T3, and BSI. (Book chapter)

Watts, S., White, D, M., & Malm, A. AI in Policing: Capturing Police Performance (Good and Bad) in Routine, Rare, and Novel Events. (Book Chapter)

White, M. D., Watts, S., & Malm, A. (2025). An Evaluation of Truleo’s AI-based Body-Worn Camera Analytics. (Preliminary findings: [pre-print](https://www.crimrxiv.com/pub/hy6q0g5t))

# Publications

[Google Scholar Profile](https://scholar.google.com/citations?user=_zgKKS0AAAAJ&hl=en&oi=ao): total citations = 173, h-index = 7, i10-index = 6

## Peer-Reviewed Journal Articles

1. **Watts, S.**, del Pozo, B., White, D. M., & Malm, A. (2025) Implementation Science Natural Experiment: Does Automated Feedback Impact Officers’ Perceptions? *Journal of Experimental Criminology*. [(DOI)](https://doi.org/10.1007/s11292-025-09711-7)

1. White, M. D., **Watts, S.**, Malm, A., & Navarrete, G. B. (2025). Officer Acceptance and Use of AI-Driven Body-Worn Camera Footage Review. *American Journal of Criminal Justice*. ([pre-print](https://doi.org/10.21428/cb6ab371.291631e5)) [(DOI)](https://doi.org/10.1007/s12103-025-09857-0)

1. White, M. D., Orosco, C., & **Watts, S**. (2025) Beyond Force and Injuries: Examining Alternative (and Important) Outcomes for Police De-escalation Training. *Journal of Criminal Justice*, 89, 102129. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235223001009?casa_token=OxErc72pD-QAAAAA:XATyRNg9im-Y4tSAmatE2RofJft49bpMx7c4_fOCiLyqIILE_rMDU03IA2yVHSmdepnLIrpzNfw))

1. Brown, K., **Watts, S**., Turner, P., & Wallace, D. (2025). How Does Proximity to Service Providers Impact Punitivity in Stop Outcomes for Individuals Experiencing Homelessness? *Journal of Crime and Justice*, 1-19. ([DOI](https://doi-org.ezproxy1.lib.asu.edu/10.1080/0735648X.2024.2375371))

1. **Watts, S**., White, M. D., Malm, A., & Perrone, D. (2024). Who is Fatigued? Examining Officer Attitudes Towards People Who Use Opioids, Naloxone, and Their Role in Responding to Opioid Overdoses. *Journal of Criminal Justice*, 95, 102308. [(DOI)](https://doi.org/10.1016/j.jcrimjus.2024.102308) 

1. **Watts, S**., White, M. D., & Malm, A. (2024). Automating Body-Worn Camera Footage Review through AI: Preliminary Findings from a Multi-Site Randomized Control Trial. *Policing: A Journal of Policy and Practice*, 18, paae107. [(pre-print)](https://www.crimrxiv.com/pub/8xm0r2jv/release/1) [(DOI)](https://doi.org/10.1093/police/paae107)

1. White, M. D., Monk, K., & **Watts, S**. (2023). A Half-Century Investigation of Police Officer Line-of-Duty Deaths: Putting Recent Trends in Long-Term Context. *Police Practice and Research*, 1-18. ([DOI](https://www-tandfonline-com.ezproxy1.lib.asu.edu/doi/abs/10.1080/15614263.2023.2267728))

1. White, D. M., Orosco, C., & **Watts, S**. (2023). Can De-escalation Training Reduce Use of Force and Citizen Injury Without Compromising Officer Safety? *Journal of Experimental Criminology*, 1-26. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s11292-023-09584-8))

1. White, M. D., **Watts, S**., Orosco, C., Malm, A., & Perrone, D. (2022). Leveraging Body-Worn Camera Footage to Better Understand Opioid Overdoses and the Impact of Police-Led Naloxone Programs. *American Journal of Public Health*, *112*(9), 1326-1332. ([DOI](https://ajph.aphapublications.org/doi/abs/10.2105/AJPH.2022.306918))

1. Gaub, J., White, M., Malm, A., **Watts, S**., & Brown, K. (2022). Investigation the Role and Utility of Body-Worn Cameras at the “George Floyd” Protests. *Policing: An International Journal*, *45*(4), 633-647. ([DOI](https://www.emerald.com/insight/content/doi/10.1108/PIJPSM-10-2021-0151/full/html))

1. White, M. D., Perrone, D., & **Watts, S**., & Malm, A. (2021). Moving Beyond Narcan: A Police, Social Service, and Researcher Collaborative Response to the Opioid Crisis. *American Journal of Criminal Justice*, *46*(4), 626-643. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s12103-021-09625-w))

1. White, M. D., Malm, A., Perrone, D., & **Watts, S**. (2021). Narcan Cops: Officer Perceptions of Opioid Use and Willingness to Carry Naloxone. *Journal of Criminal Justice*, 72, 101778. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235220302725?casa_token=M3KzLm4DIoUAAAAA:KhQQ6E6WpFcNQdyfTN33-SRHRPttqc81ijlWaNX0wOOYu3TiHBIa17DzDZS2_7K_vU9_CQwdAaA))

## Study Pre-registrations

Seth Watts, Michael D. White, & Aili Malm. "A Process and Outcome Evaluation of Automated Body-Worn Camera Review Technology in 3 Arizona Police Departments." [Registered at OSF. Embargoed (pending results).](https://osf.io/vdycb/)

## Research Briefs & Technical Reports

1. Orosco, C., White, M. D., & **Watts, S**. Can de-escalation training reduce use of force and injuries to citizens without risking officer safety? *Applied Police Briefings*. ([PDF](https://appliedpolicebriefings.com/index.php/APB/article/view/4996/3702))

1. **Watts, S**., White, M. D., Malm, A., Orosco, C., & Perrone, D. Understanding Police Involvement at Opioid Overdose Incidents Through Body-Worn Camera Footage. *Applied Police Briefings*. ([PDF](https://appliedpolicebriefings.com/index.php/APB/article/view/5019/3605))

1. White, M. D., Orosco, C., & **Watts, S**. More than Use of Force: Examining Alternative Outcomes for Police De-escalation. *Applied Police Briefings*. ([PDF](https://appliedpolicebriefings.com/index.php/APB/article/view/5010/3597))

1. White, M. D., **Watts, S**., Malm, A. A Process and Outcome Evaluation of Automated Body-Worn Camera Review Technology in 3 Arizona Police Departments, 6-month interim report. *Arnold Ventures*.

1. **Watts, S**., White, M. D., Malm, A., Perrone, D. (2023) The Tempe First-Responder Opioid Recovery Project, Year 4 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

1. **Watts, S**., White, M. D., Malm, A., Perrone, D. (2022) The Tempe First-Responder Opioid Recovery Project, Year 3 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

1. White, M. D., **Watts, S**., Malm, A., Perrone, D. (2021) The Tempe First-Responder Opioid Recovery Project, Year 2 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

1. White, M. D., **Watts, S**., Malm, A., Perrone, D. (2020) The Tempe First-Responder Opioid Recovery Project, Year 1 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

# Grant Activity

*Graduate Research Assistant & Postdoctoral Researcher* \hfill 2020-2025

A Process and Outcome Evaluation of Truleo's Automated Body-Worn Camera Review Technology in Three Arizona Police Departments.
Funded by: Arnold Ventures. 2024 - 2025 ($501,238).
Supervisor: Dr. Michael D. White

The Effect of Automated Body-Camera Review on Officers’ Professionalism and Behavioral Outcomes. 
Funded by: Arnold Ventures. June – December 2023 ($99,980; planning grant).
Supervisor: Dr. Michael D. White

The Tempe First-Responder Opioid Recovery Project
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Substance Abuse and Mental Health Services administration. 2020 – 2023 ($400,000).
Supervisor: Dr. Michael D. White

Technical Assistance Provider for the National Body-Worn Camera Pilot Implementation Program 
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Bureau of Justice Assistance. 2020 – 2022 ($800,000).
Supervisor: Dr. Michael D. White 

# Media

Salsgiver, J. (January 20, 2026) SMPD trains eligible officers in mental health. *University Star*. ([Link](https://universitystar.com/34222/news/smpd-trains-eligible-officers-in-mental-health/))

Salsgiver, J. (January 9, 2026). San Marcos sees decline in fentanyl overdoses. *University Star*. ([Link](https://universitystar.com/34152/news/san-marcos-sees-decline-in-fentanyl-overdoses/))

Goacher, D. (February 8, 2024). Tempe City Council Funds Project Addressing Opioid Overdose Response, Counseling. *Arizona State Press*. ([Link](https://www.statepress.com/article/2024/02/tempe-first-responder-opioid))

Watts, S. (September 16, 2022). Research Backs Police Response To Drug Overdoses. *Crime and Justice News*. ([Link](https://www.ncja.org/crimeandjusticenews/research-backs-police-response-to-drug-overdoses)) 

White D. M., Perrone, D., Malm, A., & Watts, S. (September 16, 2021). The Tempe First-Responder Opioid Recovery Project. *Public Health Post*. ([Link](https://www.publichealthpost.org/research/tempe-opioid-recovery/))


## Conference Presentations^[Presented by coauthor ($P$)]

Watts, S., White, M. D., & Malm, A. (November, 2025). Can AI-Driven Body-Worn Camera Review Improve Police Officer Professionalism? Findings from Three Randomized Control Trials in Arizona. *American Society of Criminology*. *Sponsored by the Division of Experimental Criminology*. 

Watts, S., White, M. D., & Malm, A. (April, 2025). Perceptions, Use, and Impact of Truleo in Three Arizona Law Enforcement Agencies. *American Society of Evidence-Based Policing*.

Abrica, C., White, M. D., Malm, A., & Watts, S. (February, 2025). A process
evaluation of AI-driven body-worn camera review: Assessing officer perceptions pre and
post. *Western Society of Criminology conference*.$^P$

Watts, S., White, M. D., & Malm, A. (November, 2024). How do Officers Perceive AI-based BWC Review Technology? Evidence from 6 Months of Survey Data. *American Society of Criminology*. *Sponsored by the division of Policing*.

White, M. D., Malm, A., & Watts, S. (November, 2024). Automating Body-Worn Camera Footage Review Through AI:
Preliminary Findings from a Multi-Site Randomized Control Trial. American Society of Criminology. *Sponsored by the division of Experimental Criminology*.$^P$

Watts, S. & White, M. D. (November, 2024). Collaborative Post-Overdose Outreach Efforts to Engage Homeless Individuals. *American Society of Criminology*.

White, M. D. & Watts, S. (June, 2024). Exploring the Drivers of Resistance to Police-Led Naloxone Programs. *American Society of Evidence-Based Policing*. 

Gutierrez, S., Mathis, S., Sanuth, A., Watts, S., & Wallace, D. (February, 2024). Is Law-Violating Driving Behavior Race Specific? Mapping Rates of At-Fault Traffic Accidents by Race. *Western Society of Criminology*.$^P$

Watts, S., White, M. D., Malm, A., & Perrone, D. (November, 2023). The Durability of Police Officers’ Attitudes about Naloxone and Opioid Overdose Response: ‘Narcan Cops’ Revisited. *American Society of Criminology*.

Watts, S., White, M. D., Malm, A., & Perrone, D. (November, 2022). The Tempe First Responder Opioid Recovery Project. *American Society of Criminology*.

White, M. D., Watts, S., Orosco, C., Malm, A., & Perrone, D (March, 2022). Myth busting Police-Led Naloxone Programs with Body-Worn Camera Footage. *Academy of Criminal Justice Sciences*. 

White, M. D., Orosco, C. A., Watts, S., Malm, A., & Perrone, D (2020). The Tempe First Responder Opioid Recovery Project. *Southern Criminal Justice Association*.$^P$

## Other Presentations
Watts, S. Repeatability, Reproducibility, and Replicability: Developing Transparent and Efficient Workflows. (November, 2025). Texas State University CJ "brown bag" series.

White, M. D., Watts, S., & Malm, A. (March, 2025). Perceptions, use, and impact of Truleo in three Arizona law enforcement agencies. Truleo’s AI Innovation Day.$^P$

White, M. D. & Watts, S. (January, 2024). Making the Invisible Visible: Body-Worn Cameras as a Tool for Uncovering Bad (and Good) Policing. ASU CCJ Colloquium Series. 

# Teaching Experience

*Texas State University*

CJ: 4310 Special Problems in the Criminal Justice System (In-person) \hfill Spring 2026

CJ: 4310 Special Problems in the Criminal Justice System (Online) \hfill Fall 2025

# Awards

American Society of Criminology, Division of Policing Outstanding Dissertation Award  \hfill 2025

American Society of Criminology, Division of Policing Travel Award   \hfill 2024

# Activities and Service

## Guest Lectures and Workshops

"[Graphics in Stata](https://github.com/sBwatts/figure-making-stata)," workshop at Arizona State University. September 20, 2024.

"[Table-making in Stata](https://github.com/sBwatts/table-making-stata)," workshop at Arizona State University. April 12, 2024.


## Conferences Attended

Academy of Criminal Justice Sciences \hfill 2022

American Society of Criminology \hfill 2022, 2023, 2024, 2025

American Society of Evidence-Based Policing  \hfill 2024, 2025


## Manuscript Reviews

*Criminal Justice & Behavior*

*Journal of Drug Issues*

*Journal of Experimental Criminology*

*Journal of Harm Reduction*

*Police Practice and Research: An International Journal*

*Policing: A Journal of Policy and Practice*

*Policing: An International Journal*


# Professional Affiliations

American Society of Evidence-Based Policing

American Society of Criminology

Western Society of Criminology 


# References

Available upon request.
